app:
  name: rag-llmops
  environment: dev

logging:
  level: INFO
  log_dir: logs
  file_enabled: true
  console_enabled: true
  file_name_prefix: app
  json: true

llm:
  groq:
    provider: "groq"
    model_name: "openai/gpt-oss-20b"
    temperature: 0
    max_output_tokens: 2048

embedding_model:
  model_name: google/embeddinggemma-300m
  device: cpu
  normalize_embeddings: true